/**
 * Documentation Catalog
 * 
 * Auto-generated by scripts/generate-docs-catalog.js
 * DO NOT EDIT MANUALLY - Run 'npm run generate:docs' to regenerate
 * 
 * Scans:
 * - public/docs/
 * - docs/
 * - src/modules/core/
 * 
 * Last generated: 2025-01-23T12:00:00.000Z
 */

export interface DocumentMetadata {
  id: string;
  title: string;
  description: string;
  category: 'Platform' | 'Architecture' | 'Development' | 'Implementation' | 'Modules' | 'Capabilities' | 'Templates';
  subcategory?: string;
  path: string;
  source?: string;
  tags?: string[];
  lastUpdated?: string;
}

export const documentationCatalog: DocumentMetadata[] = [
  {
    id: "docs-architecture",
    title: "Platform Architecture",
    description: "This document describes the overall system architecture for the multitenant platform.",
    category: "Architecture",
    subcategory: null,
    path: "docs/architecture.md",
    source: "docs/architecture.md",
    tags: ["architecture"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-database-naming-conventions",
    title: "Database Naming Conventions",
    description: "This document defines the naming conventions for database objects in the platform to ensure clarity, maintainability, and proper isolation between platform, core, and app-specific data.",
    category: "Architecture",
    subcategory: null,
    path: "docs/database-naming-conventions.md",
    source: "docs/database-naming-conventions.md",
    tags: ["database", "naming", "conventions"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-tenants",
    title: "Tenant-modell",
    description: "Systemet bruker en shared database, shared schema tilnærming med Row-Level Security (RLS) for dataisolering.",
    category: "Architecture",
    subcategory: null,
    path: "docs/tenants.md",
    source: "docs/tenants.md",
    tags: ["tenants"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "public-docs-database-naming-conventions",
    title: "Database Naming Conventions",
    description: "This document defines the naming conventions for database objects in the platform to ensure clarity, maintainability, and proper isolation between platform, core, and app-specific data.",
    category: "Architecture",
    subcategory: null,
    path: "public/docs/database-naming-conventions.md",
    source: "public/docs/database-naming-conventions.md",
    tags: ["database", "naming", "conventions"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-capabilities-ai-generation",
    title: "AI-Generated Applications",
    description: "Capability for generating complete applications using AI from natural language descriptions or website URLs.",
    category: "Capabilities",
    subcategory: null,
    path: "docs/capabilities/ai-generation.md",
    source: "docs/capabilities/ai-generation.md",
    tags: ["capabilities", "generation"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-capabilities-invitation-system",
    title: "Invitation System",
    description: "Capability for inviting users to workspaces with role-based access control and email verification.",
    category: "Capabilities",
    subcategory: null,
    path: "docs/capabilities/invitation-system.md",
    source: "docs/capabilities/invitation-system.md",
    tags: ["capabilities", "invitation", "system"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-capabilities-task-management",
    title: "Task Management",
    description: "Capability for creating, assigning, and tracking tasks with context-aware creation and notifications.",
    category: "Capabilities",
    subcategory: null,
    path: "docs/capabilities/task-management.md",
    source: "docs/capabilities/task-management.md",
    tags: ["capabilities", "task", "management"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-capabilities-overview",
    title: "Capabilities System Overview",
    description: "Oversikt over capabilities-systemet med arkitektur, datamodell og lifecycle-diagrammer.",
    category: "Capabilities",
    subcategory: null,
    path: "docs/capabilities/capabilities-overview.md",
    source: "docs/capabilities/capabilities-overview.md",
    tags: ["capabilities", "overview", "architecture"],
    lastUpdated: "2025-01-13T12:00:00.000Z"
  },
  {
    id: "docs-supplier-evaluation",
    title: "Supplier Evaluation Module",
    description: "Komplett guide til leverandørevaluering med AI-scoring, risikovurdering og rapportgenerering.",
    category: "Modules",
    subcategory: "Supplier",
    path: "docs/supplier-evaluation.md",
    source: "docs/supplier-evaluation.md",
    tags: ["supplier", "evaluation", "ai", "scoring"],
    lastUpdated: "2025-01-13T12:00:00.000Z"
  },
  {
    id: "docs-dev-apps",
    title: "App Development Guide",
    description: "Guide for developing custom applications on the platform.",
    category: "Development",
    subcategory: "Guides",
    path: "docs/dev/apps.md",
    source: "docs/dev/apps.md",
    tags: ["apps"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-dev-email-setup",
    title: "Email Setup",
    description: "Configuration guide for email services and notifications.",
    category: "Development",
    subcategory: "Guides",
    path: "docs/dev/email-setup.md",
    source: "docs/dev/email-setup.md",
    tags: ["email", "setup"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-dev-jul25-n8n-workflows",
    title: "N8N Workflows",
    description: "Integration guide for N8N automation workflows.",
    category: "Development",
    subcategory: "Guides",
    path: "docs/dev/jul25-n8n-workflows.md",
    source: "docs/dev/jul25-n8n-workflows.md",
    tags: ["jul25", "workflows"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-dev-mcp-step3-secrets-signing",
    title: "MCP Secrets & Signing",
    description: "Guide for MCP integration security and secret management.",
    category: "Development",
    subcategory: "Guides",
    path: "docs/dev/mcp-step3-secrets-signing.md",
    source: "docs/dev/mcp-step3-secrets-signing.md",
    tags: ["step3", "secrets", "signing"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-dev-roles-and-permissions",
    title: "Roles and Permissions",
    description: "Complete guide to the platform's role-based access control system.",
    category: "Development",
    subcategory: "Guides",
    path: "docs/dev/roles-and-permissions.md",
    source: "docs/dev/roles-and-permissions.md",
    tags: ["roles", "permissions"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "public-docs-readme-test",
    title: "Testing Guide",
    description: "Dette prosjektet bruker Vitest som test-rammeverk med React Testing Library for komponenttesting.",
    category: "Development",
    subcategory: null,
    path: "public/docs/README.test.md",
    source: "public/docs/README.test.md",
    tags: ["readme", "test"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-implementation-summary",
    title: "Implementasjonssammendrag: App-Rollersystem",
    description: "✅ applications tabell - Lagrer tenant-spesifikke applikasjoner (ikke hardkodet) - Unikt per tenant + key - RLS policies for sikker tilgang",
    category: "Implementation",
    subcategory: null,
    path: "docs/IMPLEMENTATION_SUMMARY.md",
    source: "docs/IMPLEMENTATION_SUMMARY.md",
    tags: ["implementation", "summary"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-sprint-status",
    title: "App Registry Implementation - Sprint Status",
    description: "- Database schema with all tables - TypeScript types and Zod schemas  - Basic service layer structure",
    category: "Implementation",
    subcategory: null,
    path: "docs/SPRINT_STATUS.md",
    source: "docs/SPRINT_STATUS.md",
    tags: ["sprint", "status"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "src-modules-core-ai-readme",
    title: "AI Module - Multi-Provider Support",
    description: "AI-modulen støtter nå flere AI-leverandører per tenant, med mulighet for hver tenant å konfigurere sin egen AI-provider og API-nøkkel.",
    category: "Modules",
    subcategory: "AI",
    path: "src/modules/core/ai/README.md",
    source: "src/modules/core/ai/README.md",
    tags: ["readme"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "src-modules-core-applications-readme",
    title: "Applications Module",
    description: "Modulen håndterer forretningssystemer (ERP, CRM, HR, etc.) på tvers av tre nivåer: globale produkter, tenant-installasjoner og selskap-/prosjekttilknytninger.",
    category: "Modules",
    subcategory: "Applications",
    path: "src/modules/core/applications/README.md",
    source: "src/modules/core/applications/README.md",
    tags: ["readme"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "src-modules-core-applications-database-views",
    title: "Database Views",
    description: "Documentation for Applications module database views.",
    category: "Modules",
    subcategory: "Applications",
    path: "src/modules/core/applications/DATABASE_VIEWS.md",
    source: "src/modules/core/applications/DATABASE_VIEWS.md",
    tags: ["database", "views"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "src-modules-core-applications-performance",
    title: "Performance Analysis",
    description: "Performance testing and optimization for Applications module.",
    category: "Modules",
    subcategory: "Applications",
    path: "src/modules/core/applications/PERFORMANCE.md",
    source: "src/modules/core/applications/PERFORMANCE.md",
    tags: ["performance"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-modules",
    title: "Module System og Events",
    description: "Comprehensive guide to the platform's module system and event architecture.",
    category: "Modules",
    subcategory: null,
    path: "docs/modules.md",
    source: "docs/modules.md",
    tags: ["modules"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "public-docs-admin-permissions-mapping",
    title: "Admin Panel Permissions Mapping",
    description: "Dette dokumentet viser mappingen mellom: Permission Resources (database ressurser), Admin Navigation (menypunkter i admin-panelet), og Required Actions (nødvendig tilgangsnivå).",
    category: "Platform",
    subcategory: null,
    path: "public/docs/admin-permissions-mapping.md",
    source: "public/docs/admin-permissions-mapping.md",
    tags: ["admin", "permissions", "mapping"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "public-docs-apps",
    title: "Platform Apps vs External Systems",
    description: "Tredjepartssystemer (ERP, CRM, etc.) som bedrifter bruker: Eksempler: Visma.net ERP, HubSpot CRM, Microsoft 365",
    category: "Platform",
    subcategory: null,
    path: "public/docs/apps.md",
    source: "public/docs/apps.md",
    tags: ["apps"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-operations",
    title: "Drift og Operasjoner",
    description: "Supabase håndterer automatisk backup: - Daily backups (siste 7 dager) - Point-in-time recovery - Manuell export via Supabase Dashboard",
    category: "Platform",
    subcategory: null,
    path: "docs/operations.md",
    source: "docs/operations.md",
    tags: ["operations"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "public-docs-readme",
    title: "Welcome to your Lovable project",
    description: "Documentation for Welcome to your Lovable project",
    category: "Platform",
    subcategory: null,
    path: "public/docs/README.md",
    source: "public/docs/README.md",
    tags: ["readme"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  },
  {
    id: "docs-templates-capability-template",
    title: "Capability Template",
    description: "Template for documenting platform capabilities.",
    category: "Templates",
    subcategory: null,
    path: "docs/templates/capability-template.md",
    source: "docs/templates/capability-template.md",
    tags: ["templates", "capability", "template"],
    lastUpdated: "2025-01-23T12:00:00.000Z"
  }
];
