/**
 * Documentation Catalog
 * 
 * Auto-generated by scripts/generate-docs-catalog.js
 * DO NOT EDIT MANUALLY - Run 'npm run generate:docs' to regenerate
 * 
 * Last generated: 2025-11-26T09:57:01.568Z
 */

export interface DocumentMetadata {
  id: string;
  title: string;
  description: string;
  category: 'Platform' | 'Architecture' | 'Development' | 'Implementation' | 'Modules' | 'Capabilities' | 'Templates';
  subcategory?: string;
  path: string;
  source?: string;
  tags?: string[];
  lastUpdated?: string;
}

export const documentationCatalog: DocumentMetadata[] = [
  {
    "id": "docs-architecture",
    "title": "Arkitektur",
    "description": "subgraph \"Client Layer\"",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/architecture.md",
    "source": "docs/architecture.md",
    "tags": [
      "architecture"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "docs-architecture-patterns",
    "title": "Arkitekturmønstre",
    "description": "Dette dokumentet beskriver sentrale arkitekturmønstre brukt i plattformen og hvordan de skal anvendes konsistent.",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/architecture-patterns.md",
    "source": "docs/architecture-patterns.md",
    "tags": [
      "architecture",
      "patterns"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "public-docs-database-naming-conventions",
    "title": "Database Naming Conventions",
    "description": "This document defines the naming conventions for database objects in the platform to ensure clarity, maintainability, and proper isolation between pla",
    "category": "Architecture",
    "subcategory": null,
    "path": "public/docs/database-naming-conventions.md",
    "source": "public/docs/database-naming-conventions.md",
    "tags": [
      "database",
      "naming",
      "conventions"
    ],
    "lastUpdated": "2025-11-25T13:16:48.177Z"
  },
  {
    "id": "docs-database-naming-conventions",
    "title": "Database Naming Conventions",
    "description": "This document defines the naming conventions for database objects in the platform to ensure clarity, maintainability, and proper isolation between pla",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/database-naming-conventions.md",
    "source": "docs/database-naming-conventions.md",
    "tags": [
      "database",
      "naming",
      "conventions"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "docs-platform-tenant",
    "title": "Platform Tenant Architecture",
    "description": "The platform tenant is a special tenant in the multitenancy architecture that serves as the \"meta-tenant\" - the administrative tenant that manages all",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/platform-tenant.md",
    "source": "docs/platform-tenant.md",
    "tags": [
      "platform",
      "tenant"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "docs-platform-tenant-override-testing",
    "title": "Tenant Override for Testing",
    "description": "Tenant Override lar deg teste ulike tenant-konfigurasjoner uten å måtte deploye til forskjellige domener. Dette er spesielt nyttig under utvikling og ",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/platform/tenant-override-testing.md",
    "source": "docs/platform/tenant-override-testing.md",
    "tags": [
      "tenant",
      "override",
      "testing"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "public-docs-tenants",
    "title": "Tenant-modell",
    "description": "Systemet bruker en shared database, shared schema tilnærming med Row-Level Security (RLS) for dataisolering.",
    "category": "Architecture",
    "subcategory": null,
    "path": "public/docs/tenants.md",
    "source": "public/docs/tenants.md",
    "tags": [
      "tenants"
    ],
    "lastUpdated": "2025-11-25T13:16:48.177Z"
  },
  {
    "id": "docs-tenants",
    "title": "Tenant-modell",
    "description": "Systemet bruker en shared database, shared schema tilnærming med Row-Level Security (RLS) for dataisolering.",
    "category": "Architecture",
    "subcategory": null,
    "path": "docs/tenants.md",
    "source": "docs/tenants.md",
    "tags": [
      "tenants"
    ],
    "lastUpdated": "2025-11-25T13:16:48.173Z"
  },
  {
    "id": "docs-capabilities-ai-generation",
    "title": "AI Content Generation",
    "description": "AI-powered content generation using Lovable Cloud's built-in AI models (Gemini and GPT). Generate text, analyze data, and create intelligent responses",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/ai-generation.md",
    "source": "docs/capabilities/ai-generation.md",
    "tags": [
      "generation"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "docs-capabilities-ai-experience-generator",
    "title": "AI Experience Generator",
    "description": "Transform markdown content into dynamic, branded web experiences through AI-powered chat. Users ask questions, AI searches a content library, and gene",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/ai-experience-generator.md",
    "source": "docs/capabilities/ai-experience-generator.md",
    "tags": [
      "experience",
      "generator"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "public-docs-capabilities-ai-generation",
    "title": "AI Text Generation",
    "description": "AI Text Generation capability enables intelligent content creation, analysis, and transformation using multiple AI providers. The system supports dyna",
    "category": "Capabilities",
    "subcategory": null,
    "path": "public/docs/capabilities/ai-generation.md",
    "source": "public/docs/capabilities/ai-generation.md",
    "tags": [
      "generation"
    ],
    "lastUpdated": "2025-11-25T13:16:48.176Z"
  },
  {
    "id": "docs-capabilities-capabilities-overview",
    "title": "Capabilities System",
    "description": "Capabilities-systemet er en katalog over gjenbrukbare funksjoner, tjenester og integrasjoner som kan aktiveres per tenant eller applikasjon.",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/capabilities-overview.md",
    "source": "docs/capabilities/capabilities-overview.md",
    "tags": [
      "capabilities",
      "overview"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "public-docs-capabilities-company-management",
    "title": "Company Management",
    "description": "Company Management capability provides comprehensive organization and relationship management. It handles company registration, verification, classifi",
    "category": "Capabilities",
    "subcategory": null,
    "path": "public/docs/capabilities/company-management.md",
    "source": "public/docs/capabilities/company-management.md",
    "tags": [
      "company",
      "management"
    ],
    "lastUpdated": "2025-11-25T13:16:48.176Z"
  },
  {
    "id": "public-docs-capabilities-external-systems-integration",
    "title": "External Systems Integration",
    "description": "External Systems Integration capability enables seamless connection with third-party business applications including ERP, CRM, accounting, e-commerce,",
    "category": "Capabilities",
    "subcategory": null,
    "path": "public/docs/capabilities/external-systems-integration.md",
    "source": "public/docs/capabilities/external-systems-integration.md",
    "tags": [
      "external",
      "systems",
      "integration"
    ],
    "lastUpdated": "2025-11-25T13:16:48.176Z"
  },
  {
    "id": "docs-capabilities-integrations",
    "title": "Integrations Module",
    "description": "Integrations-modulen er kjernen for all kommunikasjon med eksterne systemer. Den tilbyr et standardisert rammeverk for å bygge, registrere og administ",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/integrations.md",
    "source": "docs/capabilities/integrations.md",
    "tags": [
      "integrations"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "docs-capabilities-invitation-system",
    "title": "Invitation System",
    "description": "Secure invitation system for onboarding external users, suppliers, and contact persons. Generates time-limited tokens and sends email invitations via ",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/invitation-system.md",
    "source": "docs/capabilities/invitation-system.md",
    "tags": [
      "invitation",
      "system"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "public-docs-capabilities-task-management",
    "title": "Task Management",
    "description": "Task Management capability provides comprehensive task creation, assignment, tracking, and notification functionality. Tasks can be linked to projects",
    "category": "Capabilities",
    "subcategory": null,
    "path": "public/docs/capabilities/task-management.md",
    "source": "public/docs/capabilities/task-management.md",
    "tags": [
      "task",
      "management"
    ],
    "lastUpdated": "2025-11-25T13:16:48.177Z"
  },
  {
    "id": "docs-capabilities-task-management",
    "title": "Task Management",
    "description": "Comprehensive task management system with support for assignees, priorities, categories, checklists, and context-aware task creation. Tasks can be lin",
    "category": "Capabilities",
    "subcategory": null,
    "path": "docs/capabilities/task-management.md",
    "source": "docs/capabilities/task-management.md",
    "tags": [
      "task",
      "management"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "public-docs-capabilities-user-authentication",
    "title": "User Authentication",
    "description": "User Authentication provides secure user registration, login, session management, and role-based access control. Built on Supabase Auth with support f",
    "category": "Capabilities",
    "subcategory": null,
    "path": "public/docs/capabilities/user-authentication.md",
    "source": "public/docs/capabilities/user-authentication.md",
    "tags": [
      "user",
      "authentication"
    ],
    "lastUpdated": "2025-11-25T13:16:48.177Z"
  },
  {
    "id": "docs-dev-apps",
    "title": "Platform Apps Developer Guide",
    "description": "This guide covers how to create, develop, and test Platform Apps using the developer toolkit.",
    "category": "Development",
    "subcategory": "Guides",
    "path": "docs/dev/apps.md",
    "source": "docs/dev/apps.md",
    "tags": [
      "apps"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "docs-development",
    "title": "Utviklerguide",
    "description": "subgraph \"1. Setup\"",
    "category": "Development",
    "subcategory": "Guides",
    "path": "docs/development.md",
    "source": "docs/development.md",
    "tags": [
      "development"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "public-docs-readme-test",
    "title": "Testing Guide",
    "description": "Dette prosjektet bruker Vitest som test-rammeverk med React Testing Library for komponenttesting.",
    "category": "Development",
    "subcategory": null,
    "path": "public/docs/README.test.md",
    "source": "public/docs/README.test.md",
    "tags": [
      "readme.test"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "public-docs-readme-ai-chat-implementation",
    "title": "AI Chat Application Implementation",
    "description": "This document describes the implementation of the AI Chat application for the Lovenest platform. The AI Chat app provides tenants with an intelligent ",
    "category": "Implementation",
    "subcategory": null,
    "path": "public/docs/README.ai-chat-implementation.md",
    "source": "public/docs/README.ai-chat-implementation.md",
    "tags": [
      "readme.ai",
      "chat",
      "implementation"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "public-docs-implementation-status-ai-experience-generator",
    "title": "AI Experience Generator - Implementation Status ✅",
    "description": "The AI Experience Generator feature has been fully implemented. All components are in place and ready for testing.",
    "category": "Implementation",
    "subcategory": null,
    "path": "public/docs/IMPLEMENTATION_STATUS_AI_EXPERIENCE_GENERATOR.md",
    "source": "public/docs/IMPLEMENTATION_STATUS_AI_EXPERIENCE_GENERATOR.md",
    "tags": [
      "implementation",
      "status",
      "experience",
      "generator"
    ],
    "lastUpdated": "2025-11-25T13:16:48.174Z"
  },
  {
    "id": "public-docs-sprint-status",
    "title": "App Registry Implementation - Sprint Status",
    "description": "- Database schema with all tables",
    "category": "Implementation",
    "subcategory": null,
    "path": "public/docs/SPRINT_STATUS.md",
    "source": "public/docs/SPRINT_STATUS.md",
    "tags": [
      "sprint",
      "status"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "public-docs-implementation-summary",
    "title": "Implementasjonssammendrag: App-Rollersystem",
    "description": "✅ applications tabell",
    "category": "Implementation",
    "subcategory": null,
    "path": "public/docs/IMPLEMENTATION_SUMMARY.md",
    "source": "public/docs/IMPLEMENTATION_SUMMARY.md",
    "tags": [
      "implementation",
      "summary"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "src-modules-core-ai-readme",
    "title": "AI Module - Multi-Provider Support",
    "description": "AI-modulen støtter nå flere AI-leverandører per tenant, med mulighet for hver tenant å konfigurere sin egen AI-provider og API-nøkkel.",
    "category": "Modules",
    "subcategory": "AI",
    "path": "src/modules/core/ai/README.md",
    "source": "src/modules/core/ai/README.md",
    "tags": [
      "readme"
    ],
    "lastUpdated": "2025-11-25T13:16:48.201Z"
  },
  {
    "id": "src-modules-core-applications-readme",
    "title": "Applications Module",
    "description": "Modulen håndterer forretningssystemer (ERP, CRM, HR, etc.) på tvers av tre nivåer: globale produkter, tenant-installasjoner og selskap-/prosjekttilkny",
    "category": "Modules",
    "subcategory": "Applications",
    "path": "src/modules/core/applications/README.md",
    "source": "src/modules/core/applications/README.md",
    "tags": [
      "readme"
    ],
    "lastUpdated": "2025-11-25T13:16:48.204Z"
  },
  {
    "id": "src-modules-core-applications-database-views",
    "title": "Database Views og Functions",
    "description": "Denne modulen tilbyr flere database views og functions som gir konsistente aliaser og forenkler queries.",
    "category": "Modules",
    "subcategory": "Applications",
    "path": "src/modules/core/applications/DATABASE_VIEWS.md",
    "source": "src/modules/core/applications/DATABASE_VIEWS.md",
    "tags": [
      "database",
      "views"
    ],
    "lastUpdated": "2025-11-25T13:16:48.203Z"
  },
  {
    "id": "src-modules-core-applications-performance",
    "title": "Performance Analysis: Database Views vs Direct Queries",
    "description": "Dette dokumentet viser resultatene av performance-testing mellom direkte table queries og de nye database views/functions.",
    "category": "Modules",
    "subcategory": "Applications",
    "path": "src/modules/core/applications/PERFORMANCE.md",
    "source": "src/modules/core/applications/PERFORMANCE.md",
    "tags": [
      "performance"
    ],
    "lastUpdated": "2025-11-25T13:16:48.203Z"
  },
  {
    "id": "src-modules-core-compliance-templates-dpia",
    "title": "Data Protection Impact Assessment (DPIA)",
    "description": "Project Name: [Enter project name]",
    "category": "Modules",
    "subcategory": "Compliance",
    "path": "src/modules/core/compliance/templates/dpia.md",
    "source": "src/modules/core/compliance/templates/dpia.md",
    "tags": [
      "dpia"
    ],
    "lastUpdated": "2025-11-25T13:16:48.214Z"
  },
  {
    "id": "docs-modules",
    "title": "Module System og Events",
    "description": "Moduler registreres i `moduleRegistry` og lastes dynamisk basert på tenant-konfigurasjon.",
    "category": "Modules",
    "subcategory": null,
    "path": "docs/modules.md",
    "source": "docs/modules.md",
    "tags": [
      "modules"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "public-docs-admin-permissions-mapping",
    "title": "Admin Panel Permissions Mapping",
    "description": "Dette dokumentet viser mappingen mellom:",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/admin-permissions-mapping.md",
    "source": "public/docs/admin-permissions-mapping.md",
    "tags": [
      "admin",
      "permissions",
      "mapping"
    ],
    "lastUpdated": "2025-11-25T13:16:48.176Z"
  },
  {
    "id": "docs-admin-permissions-mapping",
    "title": "Admin Panel Permissions Mapping",
    "description": "Dette dokumentet viser mappingen mellom:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/admin-permissions-mapping.md",
    "source": "docs/admin-permissions-mapping.md",
    "tags": [
      "admin",
      "permissions",
      "mapping"
    ],
    "lastUpdated": "2025-11-25T13:16:48.169Z"
  },
  {
    "id": "public-docs-readme-ai-experience-generator",
    "title": "AI Experience Generator - Quick Start",
    "description": "You now have a Chat-to-Webpage system! Users ask questions in a branded chat window, and AI generates beautiful, interactive web experiences on the fl",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/README.ai-experience-generator.md",
    "source": "public/docs/README.ai-experience-generator.md",
    "tags": [
      "readme.ai",
      "experience",
      "generator"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "docs-akselera",
    "title": "Akselera",
    "description": "<content trimmed for brevity>",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/akselera.md",
    "source": "docs/akselera.md",
    "tags": [
      "akselera"
    ],
    "lastUpdated": "2025-11-25T13:16:48.169Z"
  },
  {
    "id": "public-docs-readme-docs-generator",
    "title": "Automatisk Dokumentasjonskatalog",
    "description": "Systemet oppdager automatisk alle `.md` filer i `public/docs/` og genererer `src/config/documentationCatalog.ts` med metadata.",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/README.docs-generator.md",
    "source": "public/docs/README.docs-generator.md",
    "tags": [
      "readme.docs",
      "generator"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "public-docs-operations",
    "title": "Drift og Operasjoner",
    "description": "Supabase håndterer automatisk backup:",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/operations.md",
    "source": "public/docs/operations.md",
    "tags": [
      "operations"
    ],
    "lastUpdated": "2025-11-25T13:16:48.177Z"
  },
  {
    "id": "docs-operations",
    "title": "Drift og Operasjoner",
    "description": "Supabase håndterer automatisk backup:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/operations.md",
    "source": "docs/operations.md",
    "tags": [
      "operations"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "docs-email-setup",
    "title": "Email-konfigurasjon for invitasjoner",
    "description": "For å sende invitasjons-emails automatisk, må du konfigurere Resend:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/email-setup.md",
    "source": "docs/email-setup.md",
    "tags": [
      "email",
      "setup"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "docs-frontend-consistency-plan",
    "title": "Frontend Consistency Implementation Plan",
    "description": "Created: 2025-11-14",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/FRONTEND_CONSISTENCY_PLAN.md",
    "source": "docs/FRONTEND_CONSISTENCY_PLAN.md",
    "tags": [
      "frontend",
      "consistency",
      "plan"
    ],
    "lastUpdated": "2025-11-25T13:16:48.169Z"
  },
  {
    "id": "docs-innowin",
    "title": "Innowin",
    "description": "<content trimmed for brevity>",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/innowin.md",
    "source": "docs/innowin.md",
    "tags": [
      "innowin"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "docs-jul25-n8n-workflows",
    "title": "Jul25 n8n Workflows",
    "description": "Dokumentasjon for n8n workflows som brukes av Jul25-applikasjonen.",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/jul25-n8n-workflows.md",
    "source": "docs/jul25-n8n-workflows.md",
    "tags": [
      "jul25",
      "n8n",
      "workflows"
    ],
    "lastUpdated": "2025-11-25T13:16:48.171Z"
  },
  {
    "id": "docs-mcp-step8-secrets-signing",
    "title": "MCP Step 8: Secrets & Signing Implementation",
    "description": "Step 8 implements HMAC-SHA256 signing for securing tenant integration webhooks. This enables:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/mcp-step8-secrets-signing.md",
    "source": "docs/mcp-step8-secrets-signing.md",
    "tags": [
      "mcp",
      "step8",
      "secrets",
      "signing"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "docs-n8n-workflows-readme",
    "title": "n8n Workshop Workflows",
    "description": "This folder contains n8n workflow templates for the App Creation Wizard's Miro/Notion integration.",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/n8n-workflows/README.md",
    "source": "docs/n8n-workflows/README.md",
    "tags": [
      "readme"
    ],
    "lastUpdated": "2025-11-26T09:10:33.048Z"
  },
  {
    "id": "public-docs-apps",
    "title": "Platform Apps vs External Systems",
    "description": "Tredjepartssystemer (ERP, CRM, etc.) som bedrifter bruker:",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/apps.md",
    "source": "public/docs/apps.md",
    "tags": [
      "apps"
    ],
    "lastUpdated": "2025-11-25T13:16:48.176Z"
  },
  {
    "id": "docs-apps",
    "title": "Platform Apps vs External Systems",
    "description": "Tredjepartssystemer (ERP, CRM, etc.) som bedrifter bruker:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/apps.md",
    "source": "docs/apps.md",
    "tags": [
      "apps"
    ],
    "lastUpdated": "2025-11-25T13:16:48.170Z"
  },
  {
    "id": "docs-roles-and-permissions",
    "title": "Roller og Tilganger",
    "description": "Systemet har et fleksibelt rolle- og tilgangssystem basert på fem scopes:",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/roles-and-permissions.md",
    "source": "docs/roles-and-permissions.md",
    "tags": [
      "roles",
      "and",
      "permissions"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "docs-supplier-evaluation",
    "title": "Supplier Evaluation Module",
    "description": "Supplier-modulen håndterer evaluering og scoring av leverandører i forbindelse med prosjekter. Modulen støtter både manuell vurdering via spørreskjema",
    "category": "Platform",
    "subcategory": null,
    "path": "docs/supplier-evaluation.md",
    "source": "docs/supplier-evaluation.md",
    "tags": [
      "supplier",
      "evaluation"
    ],
    "lastUpdated": "2025-11-25T13:16:48.172Z"
  },
  {
    "id": "public-docs-readme",
    "title": "Welcome to your Lovable project",
    "description": "URL: https://lovable.dev/projects/9ebb9dcf-c702-43f0-b3d4-9fd31f6f8505",
    "category": "Platform",
    "subcategory": null,
    "path": "public/docs/README.md",
    "source": "public/docs/README.md",
    "tags": [
      "readme"
    ],
    "lastUpdated": "2025-11-25T13:16:48.175Z"
  },
  {
    "id": "docs-templates-capability-template",
    "title": "[Capability Name]",
    "description": "[1-2 sentences describing what this capability does and its primary purpose]",
    "category": "Templates",
    "subcategory": null,
    "path": "docs/templates/capability-template.md",
    "source": "docs/templates/capability-template.md",
    "tags": [
      "capability",
      "template"
    ],
    "lastUpdated": "2025-11-25T13:16:48.173Z"
  }
];
