/**
 * Documentation Catalog
 * 
 * Auto-generated by scripts/generate-docs-catalog.js
 * DO NOT EDIT MANUALLY - Run 'npm run generate:docs' to regenerate
 * 
 * Last generated: 2025-01-23T10:35:00.000Z
 */

export interface DocumentMetadata {
  id: string;
  title: string;
  description: string;
  category: 'Platform' | 'Architecture' | 'Development' | 'Implementation';
  path: string;
  tags?: string[];
}

export const documentationCatalog: DocumentMetadata[] = [
  {
    "id": "admin-permissions-mapping",
    "title": "Admin Panel Permissions Mapping",
    "description": "Dette dokumentet viser mappingen mellom: Permission Resources (database ressurser), Admin Navigation (menypunkter i admin-panelet), og Required Actions (nødvendig tilgangsnivå).",
    "category": "Platform",
    "path": "docs/admin-permissions-mapping.md",
    "tags": [
      "admin",
      "permissions",
      "mapping"
    ]
  },
  {
    "id": "apps",
    "title": "Platform Apps vs External Systems",
    "description": "Tredjepartssystemer (ERP, CRM, etc.) som bedrifter bruker: Eksempler: Visma.net ERP, HubSpot CRM, Microsoft 365",
    "category": "Platform",
    "path": "docs/apps.md",
    "tags": [
      "apps"
    ]
  },
  {
    "id": "database-naming-conventions",
    "title": "Database Naming Conventions",
    "description": "This document defines the naming conventions for database objects in the platform to ensure clarity, maintainability, and proper isolation between platform, core, and app-specific data.",
    "category": "Architecture",
    "path": "docs/database-naming-conventions.md",
    "tags": [
      "database",
      "naming",
      "conventions"
    ]
  },
  {
    "id": "implementation-summary",
    "title": "Implementasjonssammendrag: App-Rollersystem",
    "description": "✅ applications tabell - Lagrer tenant-spesifikke applikasjoner (ikke hardkodet) - Unikt per tenant + key - RLS policies for sikker tilgang",
    "category": "Implementation",
    "path": "docs/IMPLEMENTATION_SUMMARY.md",
    "tags": [
      "implementation",
      "summary"
    ]
  },
  {
    "id": "operations",
    "title": "Drift og Operasjoner",
    "description": "Supabase håndterer automatisk backup: - Daily backups (siste 7 dager) - Point-in-time recovery - Manuell export via Supabase Dashboard",
    "category": "Platform",
    "path": "docs/operations.md",
    "tags": [
      "operations"
    ]
  },
  {
    "id": "readme",
    "title": "Welcome to your Lovable project",
    "description": "Documentation for Welcome to your Lovable project",
    "category": "Platform",
    "path": "docs/README.md",
    "tags": [
      "readme"
    ]
  },
  {
    "id": "readme-test",
    "title": "Testing Guide",
    "description": "Dette prosjektet bruker Vitest som test-rammeverk med React Testing Library for komponenttesting.",
    "category": "Development",
    "path": "docs/README.test.md",
    "tags": [
      "readme",
      "test"
    ]
  },
  {
    "id": "sprint-status",
    "title": "App Registry Implementation - Sprint Status",
    "description": "- Database schema with all tables - TypeScript types and Zod schemas  - Basic service layer structure",
    "category": "Implementation",
    "path": "docs/SPRINT_STATUS.md",
    "tags": [
      "sprint",
      "status"
    ]
  },
  {
    "id": "tenants",
    "title": "Tenant-modell",
    "description": "Systemet bruker en shared database, shared schema tilnærming med Row-Level Security (RLS) for dataisolering.",
    "category": "Architecture",
    "path": "docs/tenants.md",
    "tags": [
      "tenants"
    ]
  }
];
